### ISSUE TITLE
An interesting fix to Haskell's layout rule

### ISSUE THREAD

**Issue by sgraf812** [pigworker/leibniz#2]
I was just browsing this repo and found https://github.com/pigworker/leibniz/blob/ec93553a222c805e5ff1071dc802d41dbe67d3c8/HaLay.lhs#L142

That's quite an interesting, compositional fix (i.e., don't need the parser in layouter) to Haskell 2010's layout rule! 

* Is it complete, or do you think there are other killer pairs? 
* Would you say that this is the way the layout rule should have been stated in the first place? (I sure do, if there is an easy argument in favor of completeness)
* Given that it's an .lhs file, it's probably a lot older than the rest of the code in this repo. Do you recall where you first encountered this idea, or is it an original one of yours?

Thanks!

**Comment by pigworker** [comment]
Good guess! HaLay.hs dates from a little earlier, being a crucial part of the Strathclyde Haskell Enhancement: https://personal.cis.strath.ac.uk/conor.mcbride/pub/she/ From the chat on that page, and some dim and distant memory, it dates from late 2008 or early 2009. Meanwhile, I built the leibniz toy hastily a few years later (I had switched from darcs to git!) as an amusement for second year undergrads. Hilariously, I revived it *this* year, for first years.

So it was all a long time ago, and I've forgotten what was in my head at the time, apart from irritation at the need to reverse-engineer something so apparently complex. Is this the simplest description available? I don't know.

My take on layout is less is more: https://pigworker.wordpress.com/2015/05/16/one-herald-layout/

**Comment by sgraf812** [comment]
Alright, thanks. I think I agree that a single layout herald (`-:`) would make things simpler, but on the other hand I'm not entirely convinced it will recover the full generality of Haskell programs such as (taking a tricky example from [here](https://gitlab.haskell.org/ghc/ghc/-/blob/0df8ce27f1c418fee1ba860f1c6575f66cae2ca7/compiler/GHC/Parser.y#L3956-3958)

```hs
  f x = case x of
    True -> False
    where y = x+1
```

With `:-` we'd perhaps write

```
  f x = case x of :-
    True -> False
    where :- y = x+1
```
But there's no way the layouter can insert the `}` before the `where` without reading `:-` first (note that the `where` gramatically must be associated to `f x = ... where ...`), so we'd lose expressivity. I'd be happy to lose it, though, and require

```
  f x = case x of :-
      True -> False
    where :- y = x+1
```
instead.
